import { useMemo, useState } from 'react';
import { generateAvailabilitySlots } from '@fresh-feel/slotboard-core/dist/slots.js';
import { CreateFlowShell } from '../../components/create/CreateFlowShell';
import { BookingPage } from '../BookingPage';
import { navigate } from '../../lib/routing';
import { useWizardDraft, validateDetails, validateAvailability } from '../../lib/wizard';
import { ApiClientError, createEventFromDraft, storeCreatedEvent } from '../../lib/api';
import { createBoardErrorMessage } from '../../lib/errorMessages';
import type { BookingEvent, TimeSlot } from '../../lib/types';

/* ─── Step 3 — /new/review ─────────────────────────────
 * Render the public booking page exactly as participants
 * will see it, using the user's draft + the slots
 * generated by the core library. The summary rail on the
 * right has "Edit" jump-backs for each section. */

export function ReviewStep() {
  const { draft } = useWizardDraft();
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | undefined>();

  const detailsErrors = useMemo(() => validateDetails(draft), [draft]);
  const availabilityErrors = useMemo(() => validateAvailability(draft), [draft]);
  const blockedFromPosting = Object.keys(detailsErrors).length > 0 || Object.keys(availabilityErrors).length > 0;

  /* Build the synthetic event + slot list for the preview. */
  const previewEvent: BookingEvent = useMemo(
    () => ({
      id: 'preview',
      title: draft.title || 'Untitled board',
      description: draft.description,
      organizerName: draft.organizerName || 'You',
      organizerEmail: draft.organizerEmail || 'you@example.com',
      timezone: draft.timezone,
      durationMinutes: draft.durationMinutes,
      allowMultipleBookings: draft.allowMultipleBookings,
      status: 'active',
      createdAt: new Date().toISOString(),
    }),
    [draft],
  );

  const previewSlots: TimeSlot[] = useMemo(() => {
    try {
      const generated = generateAvailabilitySlots({
        startDate: draft.startDate as `${number}-${number}-${number}`,
        endDate: draft.endDate as `${number}-${number}-${number}`,
        weekdays: draft.weekdays,
        dailyStart: draft.dailyStart as `${number}:${number}`,
        dailyEnd: draft.dailyEnd as `${number}:${number}`,
        durationMinutes: draft.durationMinutes,
        timezone: draft.timezone,
        blockedRanges: draft.blockedRanges.map((r) => ({
          start: r.start as `${number}:${number}`,
          end: r.end as `${number}:${number}`,
        })),
      });
      return generated.map((g, i) => ({
        id: `preview-${i}`,
        eventId: previewEvent.id,
        startsAt: g.startsAt,
        endsAt: g.endsAt,
        state: 'open' as const,
      }));
    } catch {
      return [];
    }
  }, [draft, previewEvent.id]);

  const onPost = async () => {
    if (blockedFromPosting) {
      /* Send them back to the first invalid step. */
      navigate(Object.keys(detailsErrors).length > 0 ? '/new' : '/new/availability');
      return;
    }
    setSubmitting(true);
    setSubmitError(undefined);
    try {
      const created = await createEventFromDraft(draft);
      storeCreatedEvent(created);
      navigate('/new/done');
    } catch (error) {
      setSubmitError(
        error instanceof ApiClientError
          ? createBoardErrorMessage(error)
          : 'Could not post this board. Check the API is running and try again.',
      );
    } finally {
      setSubmitting(false);
    }
  };

  const weekdayLabel = (n: number): string => {
    const labels = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    return labels[n] ?? '';
  };

  return (
    <CreateFlowShell
      step="review"
      eyebrow="LAST LOOK"
      title="Review your board."
      body="This is exactly what participants will see. Edit any section, or post it now and start sharing."
      wide
    >
      <div className="review-layout">
        <div className="review-preview-frame">
          <BookingPage
            publicToken="preview"
            event={previewEvent}
            slots={previewSlots}
          />
        </div>

        <aside className="review-summary" aria-label="Review summary">
          <section className="review-summary__panel">
            <header className="review-summary__head">
              <span className="review-summary__eyebrow">DETAILS</span>
              <button
                type="button"
                className="review-summary__edit"
                onClick={() => navigate('/new')}
              >
                Edit
              </button>
            </header>
            <dl className="review-summary__row">
              <dt>Title</dt>
              <dd>{draft.title || '—'}</dd>
              <dt>Duration</dt>
              <dd>
                <span className="mono">{draft.durationMinutes}</span> minutes
              </dd>
              <dt>Organizer</dt>
              <dd>
                {draft.organizerName || '—'}
                <span className="sub">{draft.organizerEmail || '—'}</span>
              </dd>
              <dt>Multiple</dt>
              <dd>{draft.allowMultipleBookings ? 'Allowed' : 'One per person'}</dd>
            </dl>
          </section>

          <section className="review-summary__panel">
            <header className="review-summary__head">
              <span className="review-summary__eyebrow">AVAILABILITY</span>
              <button
                type="button"
                className="review-summary__edit"
                onClick={() => navigate('/new/availability')}
              >
                Edit
              </button>
            </header>
            <dl className="review-summary__row">
              <dt>Range</dt>
              <dd>
                <span className="mono">{draft.startDate}</span> → <span className="mono">{draft.endDate}</span>
              </dd>
              <dt>Days</dt>
              <dd>{draft.weekdays.length === 0 ? '—' : draft.weekdays.map(weekdayLabel).join(' · ')}</dd>
              <dt>Window</dt>
              <dd>
                <span className="mono">{draft.dailyStart}</span> – <span className="mono">{draft.dailyEnd}</span>
              </dd>
              <dt>Timezone</dt>
              <dd>
                <span className="mono">{draft.timezone}</span>
              </dd>
              {draft.blockedRanges.length > 0 && (
                <>
                  <dt>Breaks</dt>
                  <dd>
                    {draft.blockedRanges.map((r, i) => (
                      <div key={i}>
                        <span className="mono">{r.start}</span> – <span className="mono">{r.end}</span>
                      </div>
                    ))}
                  </dd>
                </>
              )}
              <dt>Generates</dt>
              <dd>
                <strong>
                  <span className="mono">{previewSlots.length}</span> slot{previewSlots.length === 1 ? '' : 's'}
                </strong>
              </dd>
            </dl>
          </section>
        </aside>
      </div>

      <div className="create-step__nav">
        <button
          type="button"
          className="create-step__nav-back"
          onClick={() => navigate('/new/availability')}
        >
          ← Back
        </button>
        <span className={`create-step__nav-summary${blockedFromPosting || submitError ? ' is-error' : ''}`}>
          {submitError
            ? submitError
            : blockedFromPosting
            ? 'Some fields are missing. Click to jump back.'
            : <>Ready to post · <span className="mono">{previewSlots.length}</span> slot{previewSlots.length === 1 ? '' : 's'} will be created</>}
        </span>
        <button
          type="button"
          className="create-step__nav-next"
          onClick={onPost}
          disabled={blockedFromPosting || submitting}
          aria-disabled={blockedFromPosting || submitting}
        >
          {submitting ? 'Posting…' : 'Post the board'}
        </button>
      </div>
    </CreateFlowShell>
  );
}
